spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:h2-ddl-init/init-table.sql

logging:
  level:
    root: DEBUG

